### ISSUE TITLE
Implement Docker Registry Push in CI Pipeline

### ISSUE THREAD

**Issue by pranitl** [pranitl/leadcaller#11]
## 🚀 Objective: Implement Docker Registry Push in CI Pipeline

Extend the existing CI pipeline to automatically build and push Docker images to a container registry when code is merged to main branch. This will enable automated deployment workflows and provide versioned, ready-to-deploy container images.

## 🏢 Business Context

With Docker containerization now complete (#8) and CI pipeline implementation planned (#9), the next logical step is automating the Docker image build and registry push process. This enables:

1. **Automated Image Versioning**: Each merge to main creates a tagged, deployable image
2. **Deployment Pipeline Foundation**: Ready-to-deploy images for staging/production
3. **Rollback Capability**: Tagged images enable quick rollbacks to previous versions
4. **Multi-Environment Support**: Same image can be deployed across different environments
5. **Developer Efficiency**: Eliminates manual Docker build and push steps

This is essential for our SaaS scaling goals and provides the foundation for automated deployments.

## 📋 Current State

* Docker containerization implemented with optimized Dockerfile (#8)
* CI pipeline with Node.js and Docker testing planned (#9)
* No automated image building or registry pushing
* Manual Docker builds required for deployment
* No versioning strategy for container images

### Registry Options to Consider
1. **GitHub Container Registry (ghcr.io)** - Recommended for simplicity
2. **Docker Hub** - Popular public option
3. **AWS ECR** / **Google GCR** / **Azure ACR** - Cloud provider options

#### Phase 1: Registry Setup and Authentication
```yaml
# Add to existing CI workflow
- name: Log in to Container Registry
  uses: docker/login-action@v3
  with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
```

#### Phase 2: Image Tagging Strategy
```yaml
- name: Extract metadata
  id: meta
  uses: docker/metadata-action@v5
  with:
    images: ghcr.io/${{ github.repository }}
    tags: |
      type=ref,event=branch
      type=ref,event=pr
      type=sha,prefix={{branch}}-
      type=raw,value=latest,enable={{is_default_branch}}
```

#### Phase 3: Build and Push
```yaml
- name: Build and push Docker image
  uses: docker/build-push-action@v5
  with:
    context: .
    push: true
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}
    cache-from: type=gha
    cache-to: type=gha,mode=max
```

#### Phase 4: Multi-Architecture Support (Optional)
```yaml
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3

- name: Build and push multi-arch
  uses: docker/build-push-action@v5
  with:
    platforms: linux/amd64,linux/arm64
    # ... other configs
```

### Registry Integration Testing
- [ ] Verify successful authentication to chosen registry
- [ ] Test image push for different trigger events (PR, merge, manual)
- [ ] Validate image tagging strategy works correctly
- [ ] Confirm images are pullable from registry

### Version Management Testing
- [ ] Test semantic versioning if implemented
- [ ] Verify latest tag updates correctly
- [ ] Test branch-specific tagging for feature branches
- [ ] Validate image cleanup/retention policies

### Security Testing
- [ ] Ensure registry credentials are properly secured
- [ ] Test access permissions for pushed images
- [ ] Verify image signing if implemented

### Quantitative
- [ ] Images automatically pushed to registry on main branch merges
- [ ] Build and push process completes within 10 minutes
- [ ] Zero failed pushes due to authentication or permission issues
- [ ] Proper image versioning with unique tags

### Qualitative
- [ ] Simplified deployment process using registry images
- [ ] Clear image versioning strategy for rollbacks
- [ ] Reduced manual intervention in release process
- [ ] Foundation ready for automated deployments

## ⚠️ Risks and Mitigation

| Risk | Probability | Impact | Mitigation |
|------|-------------|--------|------------|
| Registry authentication failures | Medium | High | Use GitHub tokens; test auth in staging |
| Image size/storage costs | Medium | Medium | Implement image cleanup policies |
| Build performance degradation | Low | Medium | Use build caching and multi-stage builds |
| Tag conflicts or overwrites | Low | High | Implement clear tagging strategy |

## 📅 Estimated Timeline

* **Prerequisites**: CI pipeline implementation (#9) completed
* **Day 1-2 (4-6 hours)**: Registry setup, authentication, basic push workflow
* **Day 3 (2-3 hours)**: Tagging strategy, multi-arch support, testing
* **Total Effort**: ~6-9 hours

## 🔗 Dependencies

* **Prerequisite**: #9 - CI Pipeline implementation must be completed
* **Prerequisite**: #8 - Docker containerization (✅ completed)
* **Follow-up**: Automated deployment to staging environment
* **Follow-up**: Image security scanning integration

## 📝 Implementation Notes

* Start with GitHub Container Registry for simplicity
* Implement image retention policies to manage storage costs
* Consider multi-architecture builds for broader deployment options
* Ensure proper secret management for registry credentials
* Document the new image versioning and deployment process
