### ISSUE TITLE
Integrate Security Scanning for Docker Images and Dependencies

### ISSUE THREAD

**Issue by pranitl** [pranitl/leadcaller#13]
## 🔒 Objective: Integrate Security Scanning for Docker Images and Dependencies

Implement comprehensive security scanning in the CI pipeline to automatically detect vulnerabilities in Docker images, dependencies, and container configurations. This ensures the LeadCaller application maintains high security standards before deployment.

## 🏢 Business Context

Security is paramount for a business-critical application like LeadCaller that handles sensitive lead data and integrates with external APIs. Automated security scanning provides:

1. **Proactive Vulnerability Detection**: Identify security issues before they reach production
2. **Compliance Requirements**: Meet security standards for enterprise clients
3. **Supply Chain Security**: Ensure third-party dependencies are secure
4. **Container Security**: Validate Docker image and configuration security
5. **Client Trust**: Demonstrate commitment to security for SaaS offerings
6. **Regulatory Compliance**: Support compliance with data protection regulations

This is essential for maintaining client trust and meeting enterprise security requirements as we scale.

## 📋 Current State

* Docker containerization complete with security best practices (#8)
* CI pipeline implementation planned (#9)
* No automated vulnerability scanning
* Manual dependency updates and security reviews
* No container image security validation
* Limited visibility into security posture of dependencies

#### 1. Dependency Vulnerability Scanning
```yaml
# Add to CI pipeline
dependency-scan:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  
  - name: Run npm audit
    run: |
      npm audit --audit-level=moderate
      npm audit --json > npm-audit-report.json
  
  - name: Advanced Dependency Scanning with Snyk
    uses: snyk/actions/node@master
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      args: --severity-threshold=high --file=package.json
  
  - name: Upload Dependency Scan Results
    uses: actions/upload-artifact@v4
    with:
      name: dependency-scan-results
      path: |
        npm-audit-report.json
        snyk-report.json
```

#### 2. Docker Image Security Scanning
```yaml
docker-security-scan:
  runs-on: ubuntu-latest
  needs: docker-build
  steps:
  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: 'leadcaller-app:latest'
      format: 'sarif'
      output: 'trivy-results.sarif'
      severity: 'CRITICAL,HIGH'
  
  - name: Upload Trivy scan results to GitHub Security tab
    uses: github/codeql-action/upload-sarif@v3
    with:
      sarif_file: 'trivy-results.sarif'
  
  - name: Docker Scout Scanning
    uses: docker/scout-action@v1
    with:
      command: cves
      image: leadcaller-app:latest
      only-severities: critical,high
      write-comment: true
```

#### 3. Container Configuration Security
```yaml
container-config-scan:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  
  - name: Dockerfile Security Scan with Hadolint
    uses: hadolint/hadolint-action@v3.1.0
    with:
      dockerfile: Dockerfile
      format: sarif
      output-file: hadolint-results.sarif
      no-fail: true
  
  - name: Docker Bench Security
    run: |
      docker run --rm --net host --pid host --userns host --cap-add audit_control \
        -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
        -v /etc:/etc:ro \
        -v /usr/bin/containerd:/usr/bin/containerd:ro \
        -v /usr/bin/runc:/usr/bin/runc:ro \
        -v /usr/lib/systemd:/usr/lib/systemd:ro \
        -v /var/lib:/var/lib:ro \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        --label docker_bench_security \
        docker/docker-bench-security
```

#### 4. Infrastructure as Code Security (for future Kubernetes/cloud configs)
```yaml
iac-security-scan:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  
  - name: Run Checkov IaC Scanner
    uses: bridgecrewio/checkov-action@master
    with:
      directory: .
      framework: dockerfile,kubernetes
      output_format: sarif
      output_file_path: checkov-results.sarif
```

#### 5. SAST (Static Application Security Testing)
```yaml
sast-scan:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  
  - name: Initialize CodeQL
    uses: github/codeql-action/init@v3
    with:
      languages: javascript
  
  - name: Perform CodeQL Analysis
    uses: github/codeql-action/analyze@v3
  
  - name: Semgrep Security Scan
    uses: semgrep/semgrep-action@v1
    with:
      config: auto
```

#### 1. Security Policy Definition
```yaml
# .github/security-policy.yml
security_policy:
  vulnerability_thresholds:
    critical: 0  # Block on critical vulnerabilities
    high: 2      # Allow up to 2 high severity issues
    medium: 10   # Allow up to 10 medium severity issues
  
  dependency_policies:
    auto_update: true
    exclude_dev_dependencies: false
    
  container_policies:
    require_non_root_user: true
    scan_base_images: true
    check_secrets: true
```

#### 2. Automated Security Updates
```yaml
# Dependabot configuration
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "@security-team"
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
```

### Vulnerability Detection Testing
- [ ] Test detection of known vulnerable dependencies
- [ ] Verify Docker image vulnerability scanning accuracy
- [ ] Test security policy enforcement (blocking critical issues)
- [ ] Validate security scan result reporting and notifications

### Integration Testing
- [ ] Test security scanning integration with existing CI pipeline
- [ ] Verify security scan results upload to GitHub Security tab
- [ ] Test automated security update pull requests
- [ ] Validate security scan performance impact on CI duration

### Policy Testing
- [ ] Test security threshold enforcement
- [ ] Verify security scan failure blocks deployments
- [ ] Test security scan result artifact storage
- [ ] Validate security notification workflows

### Quantitative
- [ ] Security scans complete within 10 minutes
- [ ] Zero critical vulnerabilities in production deployments
- [ ] 95% of security scans complete successfully
- [ ] Security scan results visible in GitHub Security tab

### Qualitative
- [ ] Proactive identification of security vulnerabilities
- [ ] Improved security posture visibility
- [ ] Automated security update workflow
- [ ] Enhanced confidence in deployment security
- [ ] Compliance-ready security documentation

## ⚠️ Risks and Mitigation

| Risk | Probability | Impact | Mitigation |
|------|-------------|--------|------------|
| False positives blocking deployments | Medium | Medium | Tune thresholds; implement security review process |
| Security scan performance impact | Medium | Low | Optimize scans; run in parallel with other jobs |
| Security tool configuration complexity | Medium | Medium | Use established tools; comprehensive documentation |
| Alert fatigue from too many notifications | Low | Medium | Configure appropriate severity thresholds |
| Security credentials management | Low | High | Use GitHub secrets; rotate credentials regularly |

## 📅 Estimated Timeline

* **Prerequisites**: CI pipeline implementation (#9) completed
* **Day 1-2 (6-8 hours)**: Dependency and Docker image scanning setup
* **Day 3 (4-6 hours)**: Container configuration and SAST integration
* **Day 4 (3-4 hours)**: Security policy configuration and testing
* **Day 5 (2-3 hours)**: Documentation and team training
* **Total Effort**: ~15-21 hours

## 🔗 Dependencies

* **Prerequisite**: #9 - CI Pipeline implementation
* **Prerequisite**: #8 - Docker containerization (✅ completed)
* **Enhancement**: Works alongside #11 (Docker registry push)
* **Enhancement**: Provides security validation for #12 (staging deployment)

### Tool Selection Criteria
- **Free/Open Source Options**: Trivy, npm audit, Hadolint, CodeQL
- **Commercial Options**: Snyk, Docker Scout, Aqua Security
- **Integration Quality**: GitHub Actions marketplace availability
- **Accuracy**: Low false positive rates
- **Performance**: Minimal CI pipeline impact

### Security Workflow Integration
- Integrate with GitHub Security Advisory Database
- Set up security-specific GitHub notifications
- Configure security team review requirements
- Implement security exception workflow for approved risks

### Compliance Considerations
- Maintain security scan audit trails
- Generate compliance reports from scan results
- Document security scan procedures and policies
- Ensure scan coverage meets regulatory requirements

This comprehensive security scanning implementation will significantly enhance the security posture of the LeadCaller application and provide confidence for enterprise deployments\! 🔒
